version: '3.8'

services:
  app:
    build: ./backend
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: example
      DB_NAME: catalogocine
      DB_DIALECT: mysql
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      custom_net:
        ipv4_address: 172.20.0.10

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: catalogocine
    ports:
      - "3306:3306"
    networks:
      custom_net:
        ipv4_address: 172.20.0.11

networks:
  custom_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16